/*************************************************************************
				   FUNCTION HEADERS FOR INSTRUMENTS
*************************************************************************/
extern void update_speed(plane,nav);
extern void update_lift(plane,nav);
extern void update_fuel_flow(plane);
extern void update_weight_change(float);
extern void update_dive_angle(plane,nav);
extern void update_artificial_horizon(float);
extern void update_rpm(float);
extern void update_time();
extern void update_speedometer(float);
extern void update_compass(float);
extern void update_flaps(int);
extern void update_instruments(nav,plane);
extern void update_altimeter(float);
extern void update_flaps(int);
extern void update_dme(nav);
extern void update_omi(float,nav);
extern void update_brake(int);
extern void update_climb_recorder(float);
extern void update_navigation(nav);
extern void update_bank_recorder(float);
extern void update_climb_rate(float,float);
extern void update_gear(int);
extern void update_fuel(float);
extern void update_climb_angle(float);
